# Generated by Django 5.0.2 on 2024-03-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato_Salida',
            fields=[
                ('id_datos_sal', models.AutoField(primary_key=True, serialize=False)),
                ('estado_sal', models.CharField(max_length=40)),
                ('fecha_resol', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dato de Salida',
                'verbose_name_plural': 'Datos de Salida',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Solicitud',
            fields=[
                ('id_tipo_sol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_t_sol', models.CharField(max_length=70, verbose_name='Descripción')),
                ('nombre_t_sol', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_sol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sol', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion_sol', models.CharField(max_length=70, verbose_name='Descripción')),
                ('estado_sol', models.CharField(default='s', max_length=1, verbose_name='Estado')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('notas', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_datos_sal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudesManager.dato_salida')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_tipo_sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudesManager.tipo_solicitud', verbose_name='Tipo de Solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
