# Generated by Django 5.0.2 on 2024-02-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Solicitud',
            fields=[
                ('id_tipo_sol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_t_sol', models.CharField(max_length=70, verbose_name='Descripción')),
                ('nombre_t_sol', models.CharField(max_length=25, verbose_name='Nombre')),
                ('estado_sol', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_sol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sol', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tipo_sol', models.CharField(max_length=30, verbose_name='Tipo')),
                ('descripcion_sol', models.CharField(max_length=70, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(verbose_name='Fecha de Creación')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginApp.usuario', verbose_name='Usuario')),
                ('id_tipo_sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudesManager.tipo_solicitud', verbose_name='Tipo de Solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Dato_Salida',
            fields=[
                ('id_datos_sal', models.AutoField(primary_key=True, serialize=False)),
                ('estado_sal', models.CharField(max_length=40)),
                ('fecha_resol', models.DateTimeField()),
                ('id_tipo_sol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudesManager.tipo_solicitud')),
            ],
            options={
                'verbose_name': 'Dato de Salida',
                'verbose_name_plural': 'Datos de Salida',
            },
        ),
        migrations.CreateModel(
            name='Dato_Entrada',
            fields=[
                ('id_datos_ent', models.AutoField(primary_key=True, serialize=False)),
                ('email_usuario', models.CharField(max_length=30)),
                ('nombre_cuenta', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('adjunto', models.FileField(upload_to='archivos/')),
                ('notas', models.CharField(max_length=30)),
                ('id_tipo_sol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudesManager.tipo_solicitud')),
            ],
            options={
                'verbose_name': 'Dato de Entrada',
                'verbose_name_plural': 'Datos de Entrada',
            },
        ),
    ]
