# Generated by Django 5.0.2 on 2024-03-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_sol', models.AutoField(primary_key=True, serialize=False)),
                ('estado_sol', models.CharField(default='Pendiente', max_length=25, verbose_name='Estado')),
                ('tipo_sol', models.CharField(max_length=75, verbose_name='Tipo de Solicitud')),
                ('campos_sol', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('adjunto_sol', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivos Adjuntos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
