# Generated by Django 5.0.2 on 2024-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='campos_sol',
            field=models.JSONField(verbose_name='Campos del Formulario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_sol',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Solicitud'),
        ),
    ]
