# Generated by Django 5.0.2 on 2024-02-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id_t_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=25)),
                ('estado_activacion', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_usuario', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=25)),
                ('horario_atencion', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientManager.empresa')),
                ('id_t_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginApp.tipo_usuario')),
            ],
        ),
    ]
