# Generated by Django 5.0.2 on 2024-03-01 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id_t_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=25)),
                ('estado_activacion', models.CharField(max_length=25, verbose_name='Estado de Activación')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_usuario', models.CharField(max_length=25, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=25)),
                ('horario_atencion', models.IntegerField(verbose_name='Horario de Atención')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Ingreso')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientManager.empresa', verbose_name='Empresa')),
                ('id_t_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginApp.tipo_usuario', verbose_name='Tipo de Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
