# Generated by Django 5.0.2 on 2024-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Ultimo Ingreso'),
        ),
    ]
