# Generated by Django 5.0.2 on 2024-03-28 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='casos_disponibles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, editable=False, size=None),
        ),
    ]
